name: example
description: "Example app using flutter_tweakcn_generator"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_tweakcn_generator:
    path: ../

flutter_tweakcn_generator:
  input: tweakcn.css
  output: lib/theme/tweakcn_theme.g.dart
  font_mode: local

flutter:
  fonts:
    - family: Architects Daughter
      fonts:
        - asset: fonts/ArchitectsDaughter-Regular.ttf
          weight: 400
    - family: Noto Sans KR
      fonts:
        - asset: fonts/NotoSansKR-Thin.ttf
          weight: 100
        - asset: fonts/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: fonts/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: fonts/NotoSansKR-Black.ttf
          weight: 900
  uses-material-design: true
