name: example
description: "Example app using flutter_tweakcn_generator"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_tweakcn_generator:
    path: ../

flutter_tweakcn_generator:
  input: tweakcn.css
  output: lib/theme/tweakcn_theme.g.dart

flutter:
  uses-material-design: true
