name: example
description: "Example app using flutter_tweakcn_generator"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_tweakcn_generator:
    path: ../

flutter_tweakcn_generator:
  input: tweakcn.css
  output: lib/theme/tweakcn_theme.g.dart
  font_mode: local
  font_exclusive: true

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ExtraLight.ttf
          weight: 200
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-ExtraBold.ttf
          weight: 800
        - asset: fonts/Roboto-Black.ttf
          weight: 900
  uses-material-design: true
