import 'package:pub_semver/pub_semver.dart';

import '../models/tweakcn_theme_data.dart';
import '../parser/shadow_parser.dart';
import 'color_scheme_resolver.dart';
import 'source_formatter.dart';

/// Generates a complete Dart theme file from [TweakcnThemeData].
///
/// The output includes:
/// - `ColorScheme` constants (light and dark)
/// - `ThemeExtension` classes for colors, radius, and shadows
/// - A `ThemeData` utility class with `light` and `dark` getters
/// - `BuildContext` extensions for convenient access
/// - `google_fonts` integration when a Google Font is detected in `--font-sans`
class DartThemeGenerator {
  /// Parsed theme data to generate code from.
  final TweakcnThemeData data;

  /// Prefix for all generated class names (e.g. `Tweakcn` → `TweakcnColors`).
  final String classPrefix;

  /// Font mode: `'google_fonts'`, `'local'`, or `'custom'`.
  final String fontMode;

  /// The language version to format the output at — the one the project being
  /// generated into declares, not the one this package resolves.
  ///
  /// `dart format` reads it from that project's own `environment: sdk:`
  /// constraint and formats differently across versions, so getting this wrong
  /// leaves a generated file that fails the consumer's own format check. Null
  /// formats at the newest version known, which is right for a project that
  /// declares nothing older.
  final Version? languageVersion;

  DartThemeGenerator(
    this.data, {
    this.classPrefix = 'Tweakcn',
    this.fontMode = 'google_fonts',
    this.languageVersion,
  });

  /// Generates the full Dart source code as a single string.
  String generate() {
    final buf = StringBuffer();
    final googleFonts = extractGoogleFontNames(data.resolvedFontSans);

    buf.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buf.writeln('// Generated by flutter_tweakcn_generator');
    buf.writeln();
    // `listEquals` compares the shadow levels. `material.dart` re-exports
    // foundation through a `show` clause that leaves it out, so it has to be
    // imported directly — still Flutter, still nothing else.
    buf.writeln("import 'package:flutter/foundation.dart';");
    buf.writeln("import 'package:flutter/material.dart';");
    if (googleFonts.isNotEmpty && fontMode != 'local' && fontMode != 'custom') {
      buf.writeln("import 'package:google_fonts/google_fonts.dart';");
    }
    buf.writeln();

    _writeColorSchemes(buf);
    _writeColorsExtension(buf);
    _writeRadiusExtension(buf);
    _writeShadowsExtension(buf);
    _writeThemeClass(buf, googleFonts);
    _writeBuildContextExtension(buf);

    return formatGeneratedSource(
      buf.toString(),
      languageVersion: languageVersion,
    );
  }

  // -- ColorScheme ----------------------------------------------------------

  /// The required colors of each mode, resolved once and shared by the code
  /// writer and [substitutedColorSchemeTokens].
  late final Map<String, ResolvedColorScheme> _resolvedColorSchemes = {
    'light': ColorSchemeResolver.resolve(data.light.colors, isDark: false),
    'dark': ColorSchemeResolver.resolve(data.dark.colors, isDark: true),
  };

  void _writeColorSchemes(StringBuffer buf) {
    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln('// ColorScheme');
    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln();

    _writeColorScheme(buf, 'light', data.light);
    _writeColorScheme(buf, 'dark', data.dark);
  }

  void _writeColorScheme(StringBuffer buf, String name, ThemeModeData mode) {
    // Every required property is written whether or not the theme defines it,
    // because omitting one produces a file that does not compile. The optional
    // properties are written only when the theme defines them.
    final resolvedColors = _resolvedColorSchemes[name]!.colors;

    buf.writeln('const _${name}ColorScheme = ColorScheme(');
    buf.writeln('  brightness: Brightness.$name,');

    for (final entry in ColorSchemeResolver.tokenMapping.entries) {
      final cssVar = entry.key;
      final schemeProp = entry.value;
      final color = resolvedColors[schemeProp] ?? mode.colors[cssVar];
      if (color != null) {
        buf.writeln('  $schemeProp: ${_colorLiteral(color)},');
      }
    }

    buf.writeln(');');
    buf.writeln();
  }

  /// CSS color tokens required by `ColorScheme` that this theme does not
  /// define, keyed by mode name. A fallback was substituted for each.
  ///
  /// Empty when both modes define every required token.
  Map<String, List<String>> get substitutedColorSchemeTokens => {
    for (final entry in _resolvedColorSchemes.entries)
      if (entry.value.substitutedTokens.isNotEmpty)
        entry.key: entry.value.substitutedTokens,
  };

  // -- Value equality -------------------------------------------------------

  /// Writes `operator ==` and `hashCode` over [fields].
  ///
  /// Without these an extension is equal only to itself, which cost nothing
  /// while the only instances were the baked-in constants — they are `const`,
  /// so the same one is the same object. The runtime factories build a new
  /// instance per call, and `ThemeData` compares its extensions by value: a
  /// theme rebuilt from unchanged tokens would not equal the previous one,
  /// and everything depending on `Theme.of` would rebuild.
  ///
  /// Set [fieldsAreLists] for an extension whose fields each hold a list. A
  /// list is equal only to itself too, so those are compared and hashed
  /// element-wise instead — comparing them directly would leave every instance
  /// unequal again, in the one extension where it is hardest to notice.
  void _writeValueEquality(
    StringBuffer buf,
    String cls,
    List<String> fields, {
    bool fieldsAreLists = false,
  }) {
    String compare(String field) =>
        fieldsAreLists
            ? 'listEquals($field, other.$field)'
            : '$field == other.$field';
    String hash(String field) =>
        fieldsAreLists ? 'Object.hashAll($field)' : field;

    buf.writeln('  @override');
    buf.writeln('  bool operator ==(Object other) =>');
    buf.writeln('      identical(this, other) ||');
    buf.writeln('      other is $cls &&');
    for (var i = 0; i < fields.length; i++) {
      final tail = i == fields.length - 1 ? ';' : ' &&';
      buf.writeln('          ${compare(fields[i])}$tail');
    }
    buf.writeln();

    // `Object.hash` takes at most 20 arguments and the colors extension
    // carries more tokens than that, so every one of these hashes a list.
    buf.writeln('  @override');
    buf.writeln('  int get hashCode => Object.hashAll([');
    for (final field in fields) {
      buf.writeln('    ${hash(field)},');
    }
    buf.writeln('  ]);');
  }

  // -- TweakcnColors --------------------------------------------------------

  /// All color tokens for the ThemeExtension (excluding ColorScheme ones
  /// is optional — we include ALL tokens here for direct access).
  static const _extensionColorTokens = [
    'background',
    'foreground',
    'card',
    'card-foreground',
    'popover',
    'popover-foreground',
    'primary',
    'primary-foreground',
    'secondary',
    'secondary-foreground',
    'muted',
    'muted-foreground',
    'accent',
    'accent-foreground',
    'destructive',
    'destructive-foreground',
    'border',
    'input',
    'ring',
    'chart-1',
    'chart-2',
    'chart-3',
    'chart-4',
    'chart-5',
    'sidebar',
    'sidebar-foreground',
    'sidebar-primary',
    'sidebar-primary-foreground',
    'sidebar-accent',
    'sidebar-accent-foreground',
    'sidebar-border',
    'sidebar-ring',
  ];

  void _writeColorsExtension(StringBuffer buf) {
    final cls = '${classPrefix}Colors';

    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln('// $cls (ThemeExtension)');
    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln();

    // Class definition
    buf.writeln('class $cls extends ThemeExtension<$cls> {');

    // Fields
    for (final token in _extensionColorTokens) {
      buf.writeln('  final Color ${_toCamelCase(token)};');
    }
    buf.writeln();

    // Constructor
    buf.writeln('  const $cls({');
    for (final token in _extensionColorTokens) {
      buf.writeln('    required this.${_toCamelCase(token)},');
    }
    buf.writeln('  });');
    buf.writeln();

    _writeColorsFromMap(buf, cls);
    _writeColorsInstance(buf, cls, 'light', data.light.colors);
    _writeColorsInstance(buf, cls, 'dark', data.dark.colors);

    // copyWith
    buf.writeln('  @override');
    buf.writeln('  $cls copyWith({');
    for (final token in _extensionColorTokens) {
      buf.writeln('    Color? ${_toCamelCase(token)},');
    }
    buf.writeln('  }) {');
    buf.writeln('    return $cls(');
    for (final token in _extensionColorTokens) {
      final camel = _toCamelCase(token);
      buf.writeln('      $camel: $camel ?? this.$camel,');
    }
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln();

    // lerp
    buf.writeln('  @override');
    buf.writeln('  $cls lerp(covariant $cls? other, double t) {');
    buf.writeln('    if (other == null) return this;');
    buf.writeln('    return $cls(');
    for (final token in _extensionColorTokens) {
      final camel = _toCamelCase(token);
      buf.writeln('      $camel: Color.lerp($camel, other.$camel, t)!,');
    }
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln();

    _writeValueEquality(
      buf,
      cls,
      _extensionColorTokens.map(_toCamelCase).toList(),
    );

    buf.writeln('}');
    buf.writeln();
  }

  /// Writes one of the two baked-in instances.
  void _writeColorsInstance(
    StringBuffer buf,
    String cls,
    String name,
    Map<String, int> colors,
  ) {
    buf.writeln('  static const $name = $cls(');
    for (final token in _extensionColorTokens) {
      final color = colors[token] ?? _missingColorArgb;
      buf.writeln('    ${_toCamelCase(token)}: ${_colorLiteral(color)},');
    }
    buf.writeln('  );');
    buf.writeln();
  }

  /// Writes the factory that builds the extension from parsed color tokens.
  ///
  /// A tool that parses tweakcn CSS at runtime — pasting a theme and rendering
  /// it live — reaches the same token map the generator reads, but has no way
  /// to turn it into an instance. Doing that by hand outside this package
  /// drifts silently: the generator adds a token, the copy does not, and the
  /// new color simply never updates.
  ///
  /// Written over [_extensionColorTokens] like every other member, so a token
  /// added there is a token the factory fills.
  void _writeColorsFromMap(StringBuffer buf, String cls) {
    // `Map<String, int>` rather than this package's parsed type: the generated
    // file imports Flutter and nothing else, and a consumer who takes this
    // package as a dev dependency should not have to keep it at runtime.
    buf.writeln('  /// Builds the extension from parsed tweakcn color tokens.');
    buf.writeln('  ///');
    buf.writeln(
      '  /// Keys are CSS variable names without `--`, values 32-bit ARGB.',
    );
    buf.writeln(
      '  /// A token [colors] does not carry becomes '
      '`${_colorLiteral(_missingColorArgb)}`,',
    );
    buf.writeln(
      '  /// the same placeholder [light] and [dark] use, so building from a',
    );
    buf.writeln("  /// theme's own tokens reproduces that theme's constant.");
    buf.writeln('  factory $cls.fromMap(Map<String, int> colors) => $cls(');
    for (final token in _extensionColorTokens) {
      buf.writeln(
        "    ${_toCamelCase(token)}: Color(colors['$token'] ?? "
        '${_argbLiteral(_missingColorArgb)}),',
      );
    }
    buf.writeln('  );');
    buf.writeln();
  }

  // -- TweakcnRadius --------------------------------------------------------

  /// The base radius used when the CSS declares none.
  ///
  /// Named once because the baked-in constant and the runtime factory both
  /// fall back to it, and a theme that declares no radius has to reach the
  /// same four steps either way.
  static const _defaultRadius = 8.0;

  /// Holds a step at zero rather than letting it go negative.
  ///
  /// Applied to `sm` and `md`, the two steps that sit below the base radius
  /// and so are the two a small radius can drive past zero. `lg` and `xl` are
  /// left as they are: a radius that is itself negative is the theme's own
  /// doing, and quietly correcting it here would hide it.
  ///
  /// This is not an invention either — it is what the browser does with the
  /// same CSS. `border-radius` accepts no negative length, and CSS Values 4
  /// range-checking clamps a `calc()` result to the range its property allows,
  /// so `calc(2px - 4px)` computes to `0`, not to a dropped declaration.
  static double _atLeastZero(double value) => value < 0 ? 0 : value;

  /// Writes the radius extension: four steps derived from the `--radius` token.
  ///
  /// **The derivation is tweakcn's, and this reproduces it rather than
  /// inventing one.** `utils/theme-style-generator.ts` writes the same four
  /// steps into both of tweakcn's outputs — the Tailwind v4 `@theme inline`
  /// block (`:174-177`) and the Tailwind v3 config (`:256-259`):
  ///
  /// ```css
  /// --radius-sm: calc(var(--radius) - 4px);
  /// --radius-md: calc(var(--radius) - 2px);
  /// --radius-lg: var(--radius);
  /// --radius-xl: calc(var(--radius) + 4px);
  /// ```
  ///
  /// That block travels inside the globals.css a user copies out of tweakcn,
  /// so it is what their own web app computes from the CSS they paste here.
  ///
  /// **shadcn/ui derives the same steps differently, and does not govern this
  /// layer.** Its `apps/v4/app/globals.css` (`:50-53`) scales instead — `* 0.6`,
  /// `* 0.8`, `* 1.4` — and carries three further steps tweakcn never emits.
  /// The two formulas agree at exactly one input, `--radius: 10px`, which is
  /// tweakcn's default (`config/theme.ts:53`, `0.625rem`), so every theme that
  /// leaves the radius alone hides the difference. Scaling here would make the
  /// generated theme disagree with the very CSS it was generated from, at every
  /// radius but that one. The reference routing in `CLAUDE.md` settles which
  /// wins: tweakcn owns the input, shadcn/ui is context.
  ///
  /// The whole of this is two line ranges in one upstream file — recheck them
  /// the day tweakcn's emitter moves. Reported once already, as issue #31.
  void _writeRadiusExtension(StringBuffer buf) {
    final cls = '${classPrefix}Radius';
    final radius = data.light.radius ?? data.dark.radius ?? _defaultRadius;

    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln('// $cls (ThemeExtension)');
    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln();

    buf.writeln('class $cls extends ThemeExtension<$cls> {');
    buf.writeln('  final double sm;');
    buf.writeln('  final double md;');
    buf.writeln('  final double lg;');
    buf.writeln('  final double xl;');
    buf.writeln();

    // Constructor
    buf.writeln('  const $cls({');
    buf.writeln('    required this.sm,');
    buf.writeln('    required this.md,');
    buf.writeln('    required this.lg,');
    buf.writeln('    required this.xl,');
    buf.writeln('  });');
    buf.writeln();

    _writeRadiusFromRadius(buf, cls, radius);

    // Standard instance (based on radius token)
    buf.writeln('  static const standard = $cls(');
    buf.writeln('    sm: ${_atLeastZero(radius - 4)},');
    buf.writeln('    md: ${_atLeastZero(radius - 2)},');
    buf.writeln('    lg: $radius,');
    buf.writeln('    xl: ${radius + 4},');
    buf.writeln('  );');
    buf.writeln();

    // copyWith
    buf.writeln('  @override');
    buf.writeln('  $cls copyWith({');
    buf.writeln('    double? sm,');
    buf.writeln('    double? md,');
    buf.writeln('    double? lg,');
    buf.writeln('    double? xl,');
    buf.writeln('  }) {');
    buf.writeln('    return $cls(');
    buf.writeln('      sm: sm ?? this.sm,');
    buf.writeln('      md: md ?? this.md,');
    buf.writeln('      lg: lg ?? this.lg,');
    buf.writeln('      xl: xl ?? this.xl,');
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln();

    // lerp
    buf.writeln('  @override');
    buf.writeln('  $cls lerp(covariant $cls? other, double t) {');
    buf.writeln('    if (other == null) return this;');
    buf.writeln('    return $cls(');
    buf.writeln('      sm: sm + (other.sm - sm) * t,');
    buf.writeln('      md: md + (other.md - md) * t,');
    buf.writeln('      lg: lg + (other.lg - lg) * t,');
    buf.writeln('      xl: xl + (other.xl - xl) * t,');
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln();

    _writeValueEquality(buf, cls, const ['sm', 'md', 'lg', 'xl']);

    buf.writeln('}');
    buf.writeln();
  }

  /// Writes the factory that derives the four steps from a parsed radius.
  ///
  /// The derivation lived only in this generator, so a consumer building a
  /// theme from CSS parsed at runtime had to reimplement the arithmetic and
  /// would drift from it if it ever changed.
  void _writeRadiusFromRadius(StringBuffer buf, String cls, double radius) {
    buf.writeln('  /// Builds the extension from a parsed radius, in logical');
    buf.writeln('  /// pixels.');
    buf.writeln('  ///');
    buf.writeln('  /// `lg` is the radius itself, `md` two less, `sm` four');
    buf.writeln('  /// less and `xl` four more, with `sm` and `md` held at');
    buf.writeln('  /// zero rather than going negative.');
    buf.writeln('  ///');
    buf.writeln(
      '  /// Those offsets are tweakcn\'s own, not this generator\'s:',
    );
    buf.writeln('  /// the CSS it emits derives the steps as');
    buf.writeln(
      '  /// `calc(var(--radius) - 4px)`, `calc(var(--radius) - 2px)`,',
    );
    buf.writeln(
      '  /// `var(--radius)` and `calc(var(--radius) + 4px)`. So these',
    );
    buf.writeln('  /// four values are what a browser computes from the same');
    buf.writeln(
      '  /// theme. Holding a step at zero matches it too — CSS clamps',
    );
    buf.writeln(
      '  /// a negative `calc()` result to the range `border-radius`',
    );
    buf.writeln('  /// allows. Note that shadcn/ui derives these steps by');
    buf.writeln(
      '  /// scaling instead, and the two agree only at a 10px radius.',
    );
    buf.writeln('  ///');
    buf.writeln('  /// Null means the theme declares no `--radius`, which');
    buf.writeln('  /// falls back to $_defaultRadius. [standard] is what this');
    buf.writeln(
      '  /// returns for $radius, the radius this theme resolved to.',
    );
    buf.writeln('  factory $cls.fromRadius(double? radius) {');
    buf.writeln('    final base = radius ?? $_defaultRadius;');
    buf.writeln('    double atLeastZero(double value) =>');
    buf.writeln('        value < 0 ? 0 : value;');
    buf.writeln();
    buf.writeln('    return $cls(');
    buf.writeln('      sm: atLeastZero(base - 4),');
    buf.writeln('      md: atLeastZero(base - 2),');
    buf.writeln('      lg: base,');
    buf.writeln('      xl: base + 4,');
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln();
  }

  // -- TweakcnShadows -------------------------------------------------------

  static const _shadowTokens = [
    'shadow-2xs',
    'shadow-xs',
    'shadow-sm',
    'shadow',
    'shadow-md',
    'shadow-lg',
    'shadow-xl',
    'shadow-2xl',
  ];

  void _writeShadowsExtension(StringBuffer buf) {
    final cls = '${classPrefix}Shadows';
    final layer = '${classPrefix}ShadowLayer';

    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln('// $cls (ThemeExtension)');
    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln();

    _writeShadowLayerTypedef(buf, layer);

    buf.writeln('class $cls extends ThemeExtension<$cls> {');

    // Fields
    for (final token in _shadowTokens) {
      buf.writeln('  final List<BoxShadow> ${_shadowCamelCase(token)};');
    }
    buf.writeln();

    // Constructor
    buf.writeln('  const $cls({');
    for (final token in _shadowTokens) {
      buf.writeln('    required this.${_shadowCamelCase(token)},');
    }
    buf.writeln('  });');
    buf.writeln();

    _writeShadowsFromMap(buf, cls, layer);

    // Light instance
    _writeShadowInstance(buf, cls, 'light', data.light.shadows);

    // Dark instance
    _writeShadowInstance(buf, cls, 'dark', data.dark.shadows);

    // copyWith
    buf.writeln('  @override');
    buf.writeln('  $cls copyWith({');
    for (final token in _shadowTokens) {
      buf.writeln('    List<BoxShadow>? ${_shadowCamelCase(token)},');
    }
    buf.writeln('  }) {');
    buf.writeln('    return $cls(');
    for (final token in _shadowTokens) {
      final camel = _shadowCamelCase(token);
      buf.writeln('      $camel: $camel ?? this.$camel,');
    }
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln();

    // lerp
    buf.writeln('  @override');
    buf.writeln('  $cls lerp(covariant $cls? other, double t) {');
    buf.writeln('    if (other == null) return this;');
    buf.writeln('    return $cls(');
    for (final token in _shadowTokens) {
      final camel = _shadowCamelCase(token);
      buf.writeln(
        '      $camel: BoxShadow.lerpList($camel, other.$camel, t) ?? [],',
      );
    }
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln();

    _writeValueEquality(
      buf,
      cls,
      _shadowTokens.map(_shadowCamelCase).toList(),
      fieldsAreLists: true,
    );

    buf.writeln('}');
    buf.writeln();
  }

  /// Writes the shape one shadow layer crosses into generated code in.
  ///
  /// A record, not a class from this package: the generated file imports
  /// Flutter and nothing else, and taking the parser's own shadow type here
  /// would put this package in a consumer's runtime dependencies. A record is
  /// structural, so [ThemeModeData.shadowLayers] produces exactly this type
  /// without either side importing the other.
  ///
  /// Named fields rather than a map of strings, so that misspelling one is a
  /// compile error instead of a layer that quietly loses its blur.
  void _writeShadowLayerTypedef(StringBuffer buf, String layer) {
    buf.writeln('/// One layer of one shadow level, in primitives.');
    buf.writeln('///');
    buf.writeln('/// Offsets, blur and spread are logical pixels; `color` is');
    buf.writeln('/// 32-bit ARGB. A record, so writing one by hand has its');
    buf.writeln('/// field names checked.');
    buf.writeln('typedef $layer = ({');
    buf.writeln('  double offsetX,');
    buf.writeln('  double offsetY,');
    buf.writeln('  double blurRadius,');
    buf.writeln('  double spreadRadius,');
    buf.writeln('  int color,');
    buf.writeln('});');
    buf.writeln();
  }

  /// Writes `fromShadowMap`, the factory that builds the extension from
  /// parsed shadow levels.
  ///
  /// Like the colors and radius factories, this exists because the mapping it
  /// performs lived only in this generator: a consumer building a theme from
  /// CSS parsed at runtime had to rebuild `BoxShadow` lists by hand, against a
  /// token list that would grow without them.
  ///
  /// Written over [_shadowTokens] like every other member, so a level added
  /// there is a level the factory fills.
  void _writeShadowsFromMap(StringBuffer buf, String cls, String layer) {
    buf.writeln(
      '  /// Builds the extension from parsed tweakcn shadow levels.',
    );
    buf.writeln('  ///');
    buf.writeln('  /// Keys are CSS variable names without `--`, and each');
    buf.writeln('  /// level keeps its layers in the order the CSS lists');
    buf.writeln('  /// them. A level [shadows] does not carry comes out');
    buf.writeln('  /// empty, as it does in [light] and [dark], so building');
    buf.writeln("  /// from a theme's own shadows reproduces its constant.");
    buf.writeln('  factory $cls.fromShadowMap(');
    buf.writeln('    Map<String, List<$layer>> shadows,');
    buf.writeln('  ) {');
    buf.writeln('    List<BoxShadow> level(String token) => [');
    buf.writeln(
      '      for (final layer in shadows[token] ?? const <$layer>[])',
    );
    buf.writeln('        BoxShadow(');
    buf.writeln('          offset: Offset(layer.offsetX, layer.offsetY),');
    buf.writeln('          blurRadius: layer.blurRadius,');
    buf.writeln('          spreadRadius: layer.spreadRadius,');
    buf.writeln('          color: Color(layer.color),');
    buf.writeln('        ),');
    buf.writeln('    ];');
    buf.writeln();
    buf.writeln('    return $cls(');
    for (final token in _shadowTokens) {
      buf.writeln("      ${_shadowCamelCase(token)}: level('$token'),");
    }
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln();
  }

  void _writeShadowInstance(
    StringBuffer buf,
    String cls,
    String name,
    Map<String, List<ShadowData>> shadows,
  ) {
    buf.writeln('  static const $name = $cls(');
    for (final token in _shadowTokens) {
      final shadowList = shadows[token];
      if (shadowList != null && shadowList.isNotEmpty) {
        buf.writeln('    ${_shadowCamelCase(token)}: [');
        for (final s in shadowList) {
          buf.writeln(
            '      BoxShadow('
            'offset: Offset(${s.offsetX}, ${s.offsetY}), '
            'blurRadius: ${s.blurRadius}, '
            'spreadRadius: ${s.spreadRadius}, '
            'color: ${_colorLiteral(s.color)}),',
          );
        }
        buf.writeln('    ],');
      } else {
        buf.writeln('    ${_shadowCamelCase(token)}: [],');
      }
    }
    buf.writeln('  );');
    buf.writeln();
  }

  // -- TweakcnTheme ---------------------------------------------------------

  void _writeThemeClass(StringBuffer buf, List<String> googleFonts) {
    final cls = '${classPrefix}Theme';
    final colorsCls = '${classPrefix}Colors';
    final radiusCls = '${classPrefix}Radius';
    final shadowsCls = '${classPrefix}Shadows';

    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln('// $cls');
    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln();

    buf.writeln('class $cls {');
    buf.writeln('  $cls._();');
    buf.writeln();

    // Font-related lines differ by mode
    String? fontFamilyLine;
    String? fontFamilyFallbackLine;
    String? textThemeLine;

    if (googleFonts.isNotEmpty &&
        (fontMode == 'local' || fontMode == 'custom')) {
      // Local mode: use fontFamily / fontFamilyFallback
      fontFamilyLine = "    fontFamily: '${googleFonts.first}',";
      if (googleFonts.length > 1) {
        final fallbacks = googleFonts.skip(1).map((f) => "'$f'").join(', ');
        fontFamilyFallbackLine = '    fontFamilyFallback: [$fallbacks],';
      }
    } else if (googleFonts.isNotEmpty) {
      // Google Fonts mode (default)
      final primary = _toGoogleFontsMethodName(googleFonts.first);
      if (googleFonts.length == 1) {
        textThemeLine = '    textTheme: GoogleFonts.${primary}TextTheme(),';
      } else {
        final fallbacks = googleFonts
            .skip(1)
            .map(
              (f) => 'GoogleFonts.${_toGoogleFontsMethodName(f)}().fontFamily!',
            )
            .join(', ');
        textThemeLine =
            '    textTheme: GoogleFonts.${primary}TextTheme().apply(\n'
            '      fontFamilyFallback: [$fallbacks],\n'
            '    ),';
      }
    }

    // Light theme
    buf.writeln('  static ThemeData get light => ThemeData(');
    buf.writeln('    brightness: Brightness.light,');
    buf.writeln('    colorScheme: _lightColorScheme,');
    if (fontFamilyLine != null) buf.writeln(fontFamilyLine);
    if (fontFamilyFallbackLine != null) buf.writeln(fontFamilyFallbackLine);
    if (textThemeLine != null) buf.writeln(textThemeLine);
    buf.writeln('    extensions: [');
    buf.writeln('      $colorsCls.light,');
    buf.writeln('      $radiusCls.standard,');
    buf.writeln('      $shadowsCls.light,');
    buf.writeln('    ],');
    buf.writeln('  );');
    buf.writeln();

    // Dark theme
    buf.writeln('  static ThemeData get dark => ThemeData(');
    buf.writeln('    brightness: Brightness.dark,');
    buf.writeln('    colorScheme: _darkColorScheme,');
    if (fontFamilyLine != null) buf.writeln(fontFamilyLine);
    if (fontFamilyFallbackLine != null) buf.writeln(fontFamilyFallbackLine);
    if (textThemeLine != null) buf.writeln(textThemeLine);
    buf.writeln('    extensions: [');
    buf.writeln('      $colorsCls.dark,');
    buf.writeln('      $radiusCls.standard,');
    buf.writeln('      $shadowsCls.dark,');
    buf.writeln('    ],');
    buf.writeln('  );');

    buf.writeln('}');
    buf.writeln();
  }

  // -- BuildContext Extension -----------------------------------------------

  void _writeBuildContextExtension(StringBuffer buf) {
    final colorsCls = '${classPrefix}Colors';
    final radiusCls = '${classPrefix}Radius';
    final shadowsCls = '${classPrefix}Shadows';

    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln('// BuildContext Extension');
    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln();

    buf.writeln('extension ${classPrefix}BuildContext on BuildContext {');
    buf.writeln(
      '  $colorsCls get ${_lowerFirst(classPrefix)}Colors =>'
      ' Theme.of(this).extension<$colorsCls>()!;',
    );
    buf.writeln(
      '  $radiusCls get ${_lowerFirst(classPrefix)}Radius =>'
      ' Theme.of(this).extension<$radiusCls>()!;',
    );
    buf.writeln(
      '  $shadowsCls get ${_lowerFirst(classPrefix)}Shadows =>'
      ' Theme.of(this).extension<$shadowsCls>()!;',
    );
    buf.writeln('}');
  }

  // -- Utilities ------------------------------------------------------------

  /// Converts `kebab-case` to `camelCase`.
  static String _toCamelCase(String kebab) {
    final parts = kebab.split('-');
    return parts.first +
        parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
  }

  /// Converts shadow token name to camelCase field name.
  /// `shadow-2xs` → `shadow2xs`, `shadow-md` → `shadowMd`, `shadow` → `shadow`
  static String _shadowCamelCase(String token) {
    if (token == 'shadow') return 'shadow';
    // Remove the 'shadow-' prefix, then build camelCase
    final suffix = token.substring(7); // after 'shadow-'
    // Handle numeric prefixes like '2xs', '2xl'
    if (suffix.startsWith(RegExp(r'\d'))) {
      return 'shadow$suffix';
    }
    return 'shadow${suffix[0].toUpperCase()}${suffix.substring(1)}';
  }

  static String _lowerFirst(String s) =>
      s.isEmpty ? s : s[0].toLowerCase() + s.substring(1);

  /// The color a token the theme does not define is written as.
  ///
  /// Fully transparent, so a widget reading it shows nothing rather than an
  /// arbitrary colour that looks deliberate. Named once because the constants
  /// and the runtime factory both have to use it: building from a theme's own
  /// tokens has to reproduce that theme's constants exactly, and they would
  /// disagree the moment one of the two changed.
  static const _missingColorArgb = 0x00000000;

  static String _colorLiteral(int argb) => 'Color(${_argbLiteral(argb)})';

  static String _argbLiteral(int argb) =>
      '0x${argb.toRadixString(16).padLeft(8, '0').toUpperCase()}';

  /// Generic CSS font keywords that are not Google Fonts.
  static const _genericFontKeywords = {
    'ui-sans-serif',
    'ui-serif',
    'ui-monospace',
    'system-ui',
    '-apple-system',
    'BlinkMacSystemFont',
    'sans-serif',
    'serif',
    'monospace',
    'cursive',
    'fantasy',
  };

  /// Extracts all Google Font names from a CSS font-family stack.
  ///
  /// Returns a list of font names that are not generic/system keywords.
  /// The first element is the primary font; the rest are fallbacks.
  /// e.g. `'Inter', sans-serif` → `['Inter']`
  /// e.g. `'Architects Daughter', 'Noto Sans KR', sans-serif` → `['Architects Daughter', 'Noto Sans KR']`
  /// e.g. `ui-sans-serif, system-ui, ...` → `[]`
  static List<String> extractGoogleFontNames(String? cssFontStack) {
    if (cssFontStack == null || cssFontStack.isEmpty) return [];

    final fonts = <String>[];
    for (final part in cssFontStack.split(',')) {
      final unquoted = part.trim().replaceAll(RegExp(r'''['"]'''), '').trim();
      if (unquoted.isEmpty) continue;
      // Stop collecting once we hit a generic/system keyword.
      // User-chosen Google Fonts come before system fallbacks in CSS.
      if (_genericFontKeywords.contains(unquoted)) break;
      fonts.add(unquoted);
    }
    return fonts;
  }

  /// Converts a Google Font name to its `google_fonts` package method name.
  ///
  /// e.g. `Inter` → `inter`
  /// e.g. `Noto Sans KR` → `notoSansKr`
  /// e.g. `IBM Plex Mono` → `ibmPlexMono`
  static String _toGoogleFontsMethodName(String fontName) {
    final words = fontName.trim().split(RegExp(r'\s+'));
    final buf = StringBuffer();
    for (var i = 0; i < words.length; i++) {
      final word = words[i];
      if (i == 0) {
        buf.write(word.toLowerCase());
      } else {
        buf.write(word[0].toUpperCase());
        buf.write(word.substring(1).toLowerCase());
      }
    }
    return buf.toString();
  }
}
