import '../models/tweakcn_theme_data.dart';
import '../parser/shadow_parser.dart';

/// Generates a complete Dart theme file from [TweakcnThemeData].
class DartThemeGenerator {
  final TweakcnThemeData data;
  final String classPrefix;

  DartThemeGenerator(this.data, {this.classPrefix = 'Tweakcn'});

  /// Generates the full Dart source code.
  String generate() {
    final buf = StringBuffer();

    buf.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buf.writeln('// Generated by flutter_tweakcn_generator');
    buf.writeln();
    buf.writeln("import 'package:flutter/material.dart';");
    buf.writeln();

    _writeColorSchemes(buf);
    _writeColorsExtension(buf);
    _writeRadiusExtension(buf);
    _writeShadowsExtension(buf);
    _writeThemeClass(buf);
    _writeBuildContextExtension(buf);

    return buf.toString();
  }

  // -- ColorScheme ----------------------------------------------------------

  /// Maps CSS variable names to ColorScheme property names.
  static const _colorSchemeMapping = {
    'background': 'surface',
    'foreground': 'onSurface',
    'primary': 'primary',
    'primary-foreground': 'onPrimary',
    'secondary': 'secondary',
    'secondary-foreground': 'onSecondary',
    'destructive': 'error',
    'destructive-foreground': 'onError',
    'border': 'outline',
    'input': 'outlineVariant',
    'card': 'surfaceContainerLowest',
    'muted': 'surfaceContainerHighest',
    'muted-foreground': 'onSurfaceVariant',
  };

  void _writeColorSchemes(StringBuffer buf) {
    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln('// ColorScheme');
    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln();

    _writeColorScheme(buf, 'light', data.light);
    _writeColorScheme(buf, 'dark', data.dark);
  }

  void _writeColorScheme(
    StringBuffer buf,
    String name,
    ThemeModeData mode,
  ) {
    buf.writeln(
      'const _${name}ColorScheme = ColorScheme(',
    );
    buf.writeln(
      '  brightness: Brightness.$name,',
    );

    for (final entry in _colorSchemeMapping.entries) {
      final cssVar = entry.key;
      final schemeProp = entry.value;
      final color = mode.colors[cssVar];
      if (color != null) {
        buf.writeln('  $schemeProp: ${_colorLiteral(color)},');
      }
    }

    buf.writeln(');');
    buf.writeln();
  }

  // -- TweakcnColors --------------------------------------------------------

  /// All color tokens for the ThemeExtension (excluding ColorScheme ones
  /// is optional — we include ALL tokens here for direct access).
  static const _extensionColorTokens = [
    'background',
    'foreground',
    'card',
    'card-foreground',
    'popover',
    'popover-foreground',
    'primary',
    'primary-foreground',
    'secondary',
    'secondary-foreground',
    'muted',
    'muted-foreground',
    'accent',
    'accent-foreground',
    'destructive',
    'destructive-foreground',
    'border',
    'input',
    'ring',
    'chart-1',
    'chart-2',
    'chart-3',
    'chart-4',
    'chart-5',
    'sidebar',
    'sidebar-foreground',
    'sidebar-primary',
    'sidebar-primary-foreground',
    'sidebar-accent',
    'sidebar-accent-foreground',
    'sidebar-border',
    'sidebar-ring',
  ];

  void _writeColorsExtension(StringBuffer buf) {
    final cls = '${classPrefix}Colors';

    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln('// $cls (ThemeExtension)');
    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln();

    // Class definition
    buf.writeln('class $cls extends ThemeExtension<$cls> {');

    // Fields
    for (final token in _extensionColorTokens) {
      buf.writeln('  final Color ${_toCamelCase(token)};');
    }
    buf.writeln();

    // Constructor
    buf.writeln('  const $cls({');
    for (final token in _extensionColorTokens) {
      buf.writeln('    required this.${_toCamelCase(token)},');
    }
    buf.writeln('  });');
    buf.writeln();

    // Light instance
    buf.writeln('  static const light = $cls(');
    for (final token in _extensionColorTokens) {
      final color = data.light.colors[token];
      if (color != null) {
        buf.writeln('    ${_toCamelCase(token)}: ${_colorLiteral(color)},');
      } else {
        buf.writeln(
          '    ${_toCamelCase(token)}: Color(0x00000000),',
        );
      }
    }
    buf.writeln('  );');
    buf.writeln();

    // Dark instance
    buf.writeln('  static const dark = $cls(');
    for (final token in _extensionColorTokens) {
      final color = data.dark.colors[token];
      if (color != null) {
        buf.writeln('    ${_toCamelCase(token)}: ${_colorLiteral(color)},');
      } else {
        buf.writeln(
          '    ${_toCamelCase(token)}: Color(0x00000000),',
        );
      }
    }
    buf.writeln('  );');
    buf.writeln();

    // copyWith
    buf.writeln('  @override');
    buf.writeln('  $cls copyWith({');
    for (final token in _extensionColorTokens) {
      buf.writeln('    Color? ${_toCamelCase(token)},');
    }
    buf.writeln('  }) {');
    buf.writeln('    return $cls(');
    for (final token in _extensionColorTokens) {
      final camel = _toCamelCase(token);
      buf.writeln('      $camel: $camel ?? this.$camel,');
    }
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln();

    // lerp
    buf.writeln('  @override');
    buf.writeln('  $cls lerp(covariant $cls? other, double t) {');
    buf.writeln('    if (other == null) return this;');
    buf.writeln('    return $cls(');
    for (final token in _extensionColorTokens) {
      final camel = _toCamelCase(token);
      buf.writeln(
        '      $camel: Color.lerp($camel, other.$camel, t)!,',
      );
    }
    buf.writeln('    );');
    buf.writeln('  }');

    buf.writeln('}');
    buf.writeln();
  }

  // -- TweakcnRadius --------------------------------------------------------

  void _writeRadiusExtension(StringBuffer buf) {
    final cls = '${classPrefix}Radius';
    final radius = data.light.radius ?? data.dark.radius ?? 8.0;

    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln('// $cls (ThemeExtension)');
    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln();

    buf.writeln('class $cls extends ThemeExtension<$cls> {');
    buf.writeln('  final double sm;');
    buf.writeln('  final double md;');
    buf.writeln('  final double lg;');
    buf.writeln('  final double xl;');
    buf.writeln();

    // Constructor
    buf.writeln('  const $cls({');
    buf.writeln('    required this.sm,');
    buf.writeln('    required this.md,');
    buf.writeln('    required this.lg,');
    buf.writeln('    required this.xl,');
    buf.writeln('  });');
    buf.writeln();

    // Standard instance (based on radius token)
    // Follows shadcn convention: lg = radius, md = radius - 2, sm = radius - 4, xl = radius + 4
    final lg = radius;
    final md = (radius - 2).clamp(0.0, double.infinity);
    final sm = (radius - 4).clamp(0.0, double.infinity);
    final xl = radius + 4;

    buf.writeln('  static const standard = $cls(');
    buf.writeln('    sm: $sm,');
    buf.writeln('    md: $md,');
    buf.writeln('    lg: $lg,');
    buf.writeln('    xl: $xl,');
    buf.writeln('  );');
    buf.writeln();

    // copyWith
    buf.writeln('  @override');
    buf.writeln('  $cls copyWith({');
    buf.writeln('    double? sm,');
    buf.writeln('    double? md,');
    buf.writeln('    double? lg,');
    buf.writeln('    double? xl,');
    buf.writeln('  }) {');
    buf.writeln('    return $cls(');
    buf.writeln('      sm: sm ?? this.sm,');
    buf.writeln('      md: md ?? this.md,');
    buf.writeln('      lg: lg ?? this.lg,');
    buf.writeln('      xl: xl ?? this.xl,');
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln();

    // lerp
    buf.writeln('  @override');
    buf.writeln('  $cls lerp(covariant $cls? other, double t) {');
    buf.writeln('    if (other == null) return this;');
    buf.writeln('    return $cls(');
    buf.writeln('      sm: sm + (other.sm - sm) * t,');
    buf.writeln('      md: md + (other.md - md) * t,');
    buf.writeln('      lg: lg + (other.lg - lg) * t,');
    buf.writeln('      xl: xl + (other.xl - xl) * t,');
    buf.writeln('    );');
    buf.writeln('  }');

    buf.writeln('}');
    buf.writeln();
  }

  // -- TweakcnShadows -------------------------------------------------------

  static const _shadowTokens = [
    'shadow-2xs',
    'shadow-xs',
    'shadow-sm',
    'shadow',
    'shadow-md',
    'shadow-lg',
    'shadow-xl',
    'shadow-2xl',
  ];

  void _writeShadowsExtension(StringBuffer buf) {
    final cls = '${classPrefix}Shadows';

    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln('// $cls (ThemeExtension)');
    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln();

    buf.writeln('class $cls extends ThemeExtension<$cls> {');

    // Fields
    for (final token in _shadowTokens) {
      buf.writeln('  final List<BoxShadow> ${_shadowCamelCase(token)};');
    }
    buf.writeln();

    // Constructor
    buf.writeln('  const $cls({');
    for (final token in _shadowTokens) {
      buf.writeln('    required this.${_shadowCamelCase(token)},');
    }
    buf.writeln('  });');
    buf.writeln();

    // Light instance
    _writeShadowInstance(buf, cls, 'light', data.light.shadows);

    // Dark instance
    _writeShadowInstance(buf, cls, 'dark', data.dark.shadows);

    // copyWith
    buf.writeln('  @override');
    buf.writeln('  $cls copyWith({');
    for (final token in _shadowTokens) {
      buf.writeln('    List<BoxShadow>? ${_shadowCamelCase(token)},');
    }
    buf.writeln('  }) {');
    buf.writeln('    return $cls(');
    for (final token in _shadowTokens) {
      final camel = _shadowCamelCase(token);
      buf.writeln('      $camel: $camel ?? this.$camel,');
    }
    buf.writeln('    );');
    buf.writeln('  }');
    buf.writeln();

    // lerp
    buf.writeln('  @override');
    buf.writeln('  $cls lerp(covariant $cls? other, double t) {');
    buf.writeln('    if (other == null) return this;');
    buf.writeln('    return $cls(');
    for (final token in _shadowTokens) {
      final camel = _shadowCamelCase(token);
      buf.writeln(
        '      $camel: BoxShadow.lerpList($camel, other.$camel, t) ?? [],',
      );
    }
    buf.writeln('    );');
    buf.writeln('  }');

    buf.writeln('}');
    buf.writeln();
  }

  void _writeShadowInstance(
    StringBuffer buf,
    String cls,
    String name,
    Map<String, List<ShadowData>> shadows,
  ) {
    buf.writeln('  static const $name = $cls(');
    for (final token in _shadowTokens) {
      final shadowList = shadows[token];
      if (shadowList != null && shadowList.isNotEmpty) {
        buf.writeln('    ${_shadowCamelCase(token)}: [');
        for (final s in shadowList) {
          buf.writeln(
            '      BoxShadow('
            'offset: Offset(${s.offsetX}, ${s.offsetY}), '
            'blurRadius: ${s.blurRadius}, '
            'spreadRadius: ${s.spreadRadius}, '
            'color: ${_colorLiteral(s.color)}),',
          );
        }
        buf.writeln('    ],');
      } else {
        buf.writeln('    ${_shadowCamelCase(token)}: [],');
      }
    }
    buf.writeln('  );');
    buf.writeln();
  }

  // -- TweakcnTheme ---------------------------------------------------------

  void _writeThemeClass(StringBuffer buf) {
    final cls = '${classPrefix}Theme';
    final colorsCls = '${classPrefix}Colors';
    final radiusCls = '${classPrefix}Radius';
    final shadowsCls = '${classPrefix}Shadows';

    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln('// $cls');
    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln();

    buf.writeln('class $cls {');
    buf.writeln('  $cls._();');
    buf.writeln();

    // Light theme
    buf.writeln('  static ThemeData get light => ThemeData(');
    buf.writeln('    brightness: Brightness.light,');
    buf.writeln('    colorScheme: _lightColorScheme,');
    buf.writeln('    extensions: [');
    buf.writeln('      $colorsCls.light,');
    buf.writeln('      $radiusCls.standard,');
    buf.writeln('      $shadowsCls.light,');
    buf.writeln('    ],');
    buf.writeln('  );');
    buf.writeln();

    // Dark theme
    buf.writeln('  static ThemeData get dark => ThemeData(');
    buf.writeln('    brightness: Brightness.dark,');
    buf.writeln('    colorScheme: _darkColorScheme,');
    buf.writeln('    extensions: [');
    buf.writeln('      $colorsCls.dark,');
    buf.writeln('      $radiusCls.standard,');
    buf.writeln('      $shadowsCls.dark,');
    buf.writeln('    ],');
    buf.writeln('  );');

    buf.writeln('}');
    buf.writeln();
  }

  // -- BuildContext Extension -----------------------------------------------

  void _writeBuildContextExtension(StringBuffer buf) {
    final colorsCls = '${classPrefix}Colors';
    final radiusCls = '${classPrefix}Radius';
    final shadowsCls = '${classPrefix}Shadows';

    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln('// BuildContext Extension');
    buf.writeln('// ──────────────────────────────────────────');
    buf.writeln();

    buf.writeln('extension ${classPrefix}BuildContext on BuildContext {');
    buf.writeln(
      '  $colorsCls get ${_lowerFirst(classPrefix)}Colors =>'
      ' Theme.of(this).extension<$colorsCls>()!;',
    );
    buf.writeln(
      '  $radiusCls get ${_lowerFirst(classPrefix)}Radius =>'
      ' Theme.of(this).extension<$radiusCls>()!;',
    );
    buf.writeln(
      '  $shadowsCls get ${_lowerFirst(classPrefix)}Shadows =>'
      ' Theme.of(this).extension<$shadowsCls>()!;',
    );
    buf.writeln('}');
  }

  // -- Utilities ------------------------------------------------------------

  /// Converts `kebab-case` to `camelCase`.
  static String _toCamelCase(String kebab) {
    final parts = kebab.split('-');
    return parts.first +
        parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
  }

  /// Converts shadow token name to camelCase field name.
  /// `shadow-2xs` → `shadow2xs`, `shadow-md` → `shadowMd`, `shadow` → `shadow`
  static String _shadowCamelCase(String token) {
    if (token == 'shadow') return 'shadow';
    // Remove the 'shadow-' prefix, then build camelCase
    final suffix = token.substring(7); // after 'shadow-'
    // Handle numeric prefixes like '2xs', '2xl'
    if (suffix.startsWith(RegExp(r'\d'))) {
      return 'shadow$suffix';
    }
    return 'shadow${suffix[0].toUpperCase()}${suffix.substring(1)}';
  }

  static String _lowerFirst(String s) =>
      s.isEmpty ? s : s[0].toLowerCase() + s.substring(1);

  static String _colorLiteral(int argb) {
    return 'Color(0x${argb.toRadixString(16).padLeft(8, '0').toUpperCase()})';
  }
}
