// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by flutter_tweakcn_generator

import 'package:flutter/material.dart';

// ──────────────────────────────────────────
// ColorScheme
// ──────────────────────────────────────────

const _lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  surface: Color(0xFFF9F9F9),
  onSurface: Color(0xFF3A3A3A),
  primary: Color(0xFF606060),
  onPrimary: Color(0xFFF0F0F0),
  secondary: Color(0xFFDEDEDE),
  onSecondary: Color(0xFF3A3A3A),
  error: Color(0xFFC87A7A),
  onError: Color(0xFFFFFFFF),
  outline: Color(0xFF747272),
  outlineVariant: Color(0xFFFFFFFF),
  surfaceContainerLowest: Color(0xFFFFFFFF),
  surfaceContainerHighest: Color(0xFFE3E3E3),
  onSurfaceVariant: Color(0xFF505050),
);

const _darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  surface: Color(0xFF2B2B2B),
  onSurface: Color(0xFFDCDCDC),
  primary: Color(0xFFB0B0B0),
  onPrimary: Color(0xFF2B2B2B),
  secondary: Color(0xFF5A5A5A),
  onSecondary: Color(0xFFC0C0C0),
  error: Color(0xFFD9AFAF),
  onError: Color(0xFF2B2B2B),
  outline: Color(0xFF4F4F4F),
  outlineVariant: Color(0xFF333333),
  surfaceContainerLowest: Color(0xFF333333),
  surfaceContainerHighest: Color(0xFF454545),
  onSurfaceVariant: Color(0xFFA0A0A0),
);

// ──────────────────────────────────────────
// TweakcnColors (ThemeExtension)
// ──────────────────────────────────────────

class TweakcnColors extends ThemeExtension<TweakcnColors> {
  final Color background;
  final Color foreground;
  final Color card;
  final Color cardForeground;
  final Color popover;
  final Color popoverForeground;
  final Color primary;
  final Color primaryForeground;
  final Color secondary;
  final Color secondaryForeground;
  final Color muted;
  final Color mutedForeground;
  final Color accent;
  final Color accentForeground;
  final Color destructive;
  final Color destructiveForeground;
  final Color border;
  final Color input;
  final Color ring;
  final Color chart1;
  final Color chart2;
  final Color chart3;
  final Color chart4;
  final Color chart5;
  final Color sidebar;
  final Color sidebarForeground;
  final Color sidebarPrimary;
  final Color sidebarPrimaryForeground;
  final Color sidebarAccent;
  final Color sidebarAccentForeground;
  final Color sidebarBorder;
  final Color sidebarRing;

  const TweakcnColors({
    required this.background,
    required this.foreground,
    required this.card,
    required this.cardForeground,
    required this.popover,
    required this.popoverForeground,
    required this.primary,
    required this.primaryForeground,
    required this.secondary,
    required this.secondaryForeground,
    required this.muted,
    required this.mutedForeground,
    required this.accent,
    required this.accentForeground,
    required this.destructive,
    required this.destructiveForeground,
    required this.border,
    required this.input,
    required this.ring,
    required this.chart1,
    required this.chart2,
    required this.chart3,
    required this.chart4,
    required this.chart5,
    required this.sidebar,
    required this.sidebarForeground,
    required this.sidebarPrimary,
    required this.sidebarPrimaryForeground,
    required this.sidebarAccent,
    required this.sidebarAccentForeground,
    required this.sidebarBorder,
    required this.sidebarRing,
  });

  /// Builds TweakcnColors from parsed tweakcn color tokens.
  ///
  /// Keys are CSS variable names without `--`, values 32-bit ARGB.
  /// A token [colors] does not carry becomes `Color(0x00000000)`,
  /// the same placeholder [light] and [dark] use, so building from a
  /// theme's own tokens reproduces that theme's constant.
  factory TweakcnColors.fromMap(Map<String, int> colors) => TweakcnColors(
    background: Color(colors['background'] ?? 0x00000000),
    foreground: Color(colors['foreground'] ?? 0x00000000),
    card: Color(colors['card'] ?? 0x00000000),
    cardForeground: Color(colors['card-foreground'] ?? 0x00000000),
    popover: Color(colors['popover'] ?? 0x00000000),
    popoverForeground: Color(colors['popover-foreground'] ?? 0x00000000),
    primary: Color(colors['primary'] ?? 0x00000000),
    primaryForeground: Color(colors['primary-foreground'] ?? 0x00000000),
    secondary: Color(colors['secondary'] ?? 0x00000000),
    secondaryForeground: Color(colors['secondary-foreground'] ?? 0x00000000),
    muted: Color(colors['muted'] ?? 0x00000000),
    mutedForeground: Color(colors['muted-foreground'] ?? 0x00000000),
    accent: Color(colors['accent'] ?? 0x00000000),
    accentForeground: Color(colors['accent-foreground'] ?? 0x00000000),
    destructive: Color(colors['destructive'] ?? 0x00000000),
    destructiveForeground: Color(
      colors['destructive-foreground'] ?? 0x00000000,
    ),
    border: Color(colors['border'] ?? 0x00000000),
    input: Color(colors['input'] ?? 0x00000000),
    ring: Color(colors['ring'] ?? 0x00000000),
    chart1: Color(colors['chart-1'] ?? 0x00000000),
    chart2: Color(colors['chart-2'] ?? 0x00000000),
    chart3: Color(colors['chart-3'] ?? 0x00000000),
    chart4: Color(colors['chart-4'] ?? 0x00000000),
    chart5: Color(colors['chart-5'] ?? 0x00000000),
    sidebar: Color(colors['sidebar'] ?? 0x00000000),
    sidebarForeground: Color(colors['sidebar-foreground'] ?? 0x00000000),
    sidebarPrimary: Color(colors['sidebar-primary'] ?? 0x00000000),
    sidebarPrimaryForeground: Color(
      colors['sidebar-primary-foreground'] ?? 0x00000000,
    ),
    sidebarAccent: Color(colors['sidebar-accent'] ?? 0x00000000),
    sidebarAccentForeground: Color(
      colors['sidebar-accent-foreground'] ?? 0x00000000,
    ),
    sidebarBorder: Color(colors['sidebar-border'] ?? 0x00000000),
    sidebarRing: Color(colors['sidebar-ring'] ?? 0x00000000),
  );

  static const light = TweakcnColors(
    background: Color(0xFFF9F9F9),
    foreground: Color(0xFF3A3A3A),
    card: Color(0xFFFFFFFF),
    cardForeground: Color(0xFF3A3A3A),
    popover: Color(0xFFFFFFFF),
    popoverForeground: Color(0xFF3A3A3A),
    primary: Color(0xFF606060),
    primaryForeground: Color(0xFFF0F0F0),
    secondary: Color(0xFFDEDEDE),
    secondaryForeground: Color(0xFF3A3A3A),
    muted: Color(0xFFE3E3E3),
    mutedForeground: Color(0xFF505050),
    accent: Color(0xFFF3EAC8),
    accentForeground: Color(0xFF5D4037),
    destructive: Color(0xFFC87A7A),
    destructiveForeground: Color(0xFFFFFFFF),
    border: Color(0xFF747272),
    input: Color(0xFFFFFFFF),
    ring: Color(0xFFA0A0A0),
    chart1: Color(0xFF333333),
    chart2: Color(0xFF555555),
    chart3: Color(0xFF777777),
    chart4: Color(0xFF999999),
    chart5: Color(0xFFBBBBBB),
    sidebar: Color(0xFFF0F0F0),
    sidebarForeground: Color(0xFF3A3A3A),
    sidebarPrimary: Color(0xFF606060),
    sidebarPrimaryForeground: Color(0xFFF0F0F0),
    sidebarAccent: Color(0xFFF3EAC8),
    sidebarAccentForeground: Color(0xFF5D4037),
    sidebarBorder: Color(0xFFC0C0C0),
    sidebarRing: Color(0xFFA0A0A0),
  );

  static const dark = TweakcnColors(
    background: Color(0xFF2B2B2B),
    foreground: Color(0xFFDCDCDC),
    card: Color(0xFF333333),
    cardForeground: Color(0xFFDCDCDC),
    popover: Color(0xFF333333),
    popoverForeground: Color(0xFFDCDCDC),
    primary: Color(0xFFB0B0B0),
    primaryForeground: Color(0xFF2B2B2B),
    secondary: Color(0xFF5A5A5A),
    secondaryForeground: Color(0xFFC0C0C0),
    muted: Color(0xFF454545),
    mutedForeground: Color(0xFFA0A0A0),
    accent: Color(0xFFE0E0E0),
    accentForeground: Color(0xFF333333),
    destructive: Color(0xFFD9AFAF),
    destructiveForeground: Color(0xFF2B2B2B),
    border: Color(0xFF4F4F4F),
    input: Color(0xFF333333),
    ring: Color(0xFFC0C0C0),
    chart1: Color(0xFFEFEFEF),
    chart2: Color(0xFFD0D0D0),
    chart3: Color(0xFFB0B0B0),
    chart4: Color(0xFF909090),
    chart5: Color(0xFF707070),
    sidebar: Color(0xFF212121),
    sidebarForeground: Color(0xFFDCDCDC),
    sidebarPrimary: Color(0xFFB0B0B0),
    sidebarPrimaryForeground: Color(0xFF212121),
    sidebarAccent: Color(0xFFE0E0E0),
    sidebarAccentForeground: Color(0xFF333333),
    sidebarBorder: Color(0xFF4F4F4F),
    sidebarRing: Color(0xFFC0C0C0),
  );

  @override
  TweakcnColors copyWith({
    Color? background,
    Color? foreground,
    Color? card,
    Color? cardForeground,
    Color? popover,
    Color? popoverForeground,
    Color? primary,
    Color? primaryForeground,
    Color? secondary,
    Color? secondaryForeground,
    Color? muted,
    Color? mutedForeground,
    Color? accent,
    Color? accentForeground,
    Color? destructive,
    Color? destructiveForeground,
    Color? border,
    Color? input,
    Color? ring,
    Color? chart1,
    Color? chart2,
    Color? chart3,
    Color? chart4,
    Color? chart5,
    Color? sidebar,
    Color? sidebarForeground,
    Color? sidebarPrimary,
    Color? sidebarPrimaryForeground,
    Color? sidebarAccent,
    Color? sidebarAccentForeground,
    Color? sidebarBorder,
    Color? sidebarRing,
  }) {
    return TweakcnColors(
      background: background ?? this.background,
      foreground: foreground ?? this.foreground,
      card: card ?? this.card,
      cardForeground: cardForeground ?? this.cardForeground,
      popover: popover ?? this.popover,
      popoverForeground: popoverForeground ?? this.popoverForeground,
      primary: primary ?? this.primary,
      primaryForeground: primaryForeground ?? this.primaryForeground,
      secondary: secondary ?? this.secondary,
      secondaryForeground: secondaryForeground ?? this.secondaryForeground,
      muted: muted ?? this.muted,
      mutedForeground: mutedForeground ?? this.mutedForeground,
      accent: accent ?? this.accent,
      accentForeground: accentForeground ?? this.accentForeground,
      destructive: destructive ?? this.destructive,
      destructiveForeground:
          destructiveForeground ?? this.destructiveForeground,
      border: border ?? this.border,
      input: input ?? this.input,
      ring: ring ?? this.ring,
      chart1: chart1 ?? this.chart1,
      chart2: chart2 ?? this.chart2,
      chart3: chart3 ?? this.chart3,
      chart4: chart4 ?? this.chart4,
      chart5: chart5 ?? this.chart5,
      sidebar: sidebar ?? this.sidebar,
      sidebarForeground: sidebarForeground ?? this.sidebarForeground,
      sidebarPrimary: sidebarPrimary ?? this.sidebarPrimary,
      sidebarPrimaryForeground:
          sidebarPrimaryForeground ?? this.sidebarPrimaryForeground,
      sidebarAccent: sidebarAccent ?? this.sidebarAccent,
      sidebarAccentForeground:
          sidebarAccentForeground ?? this.sidebarAccentForeground,
      sidebarBorder: sidebarBorder ?? this.sidebarBorder,
      sidebarRing: sidebarRing ?? this.sidebarRing,
    );
  }

  @override
  TweakcnColors lerp(covariant TweakcnColors? other, double t) {
    if (other == null) return this;
    return TweakcnColors(
      background: Color.lerp(background, other.background, t)!,
      foreground: Color.lerp(foreground, other.foreground, t)!,
      card: Color.lerp(card, other.card, t)!,
      cardForeground: Color.lerp(cardForeground, other.cardForeground, t)!,
      popover: Color.lerp(popover, other.popover, t)!,
      popoverForeground: Color.lerp(
        popoverForeground,
        other.popoverForeground,
        t,
      )!,
      primary: Color.lerp(primary, other.primary, t)!,
      primaryForeground: Color.lerp(
        primaryForeground,
        other.primaryForeground,
        t,
      )!,
      secondary: Color.lerp(secondary, other.secondary, t)!,
      secondaryForeground: Color.lerp(
        secondaryForeground,
        other.secondaryForeground,
        t,
      )!,
      muted: Color.lerp(muted, other.muted, t)!,
      mutedForeground: Color.lerp(mutedForeground, other.mutedForeground, t)!,
      accent: Color.lerp(accent, other.accent, t)!,
      accentForeground: Color.lerp(
        accentForeground,
        other.accentForeground,
        t,
      )!,
      destructive: Color.lerp(destructive, other.destructive, t)!,
      destructiveForeground: Color.lerp(
        destructiveForeground,
        other.destructiveForeground,
        t,
      )!,
      border: Color.lerp(border, other.border, t)!,
      input: Color.lerp(input, other.input, t)!,
      ring: Color.lerp(ring, other.ring, t)!,
      chart1: Color.lerp(chart1, other.chart1, t)!,
      chart2: Color.lerp(chart2, other.chart2, t)!,
      chart3: Color.lerp(chart3, other.chart3, t)!,
      chart4: Color.lerp(chart4, other.chart4, t)!,
      chart5: Color.lerp(chart5, other.chart5, t)!,
      sidebar: Color.lerp(sidebar, other.sidebar, t)!,
      sidebarForeground: Color.lerp(
        sidebarForeground,
        other.sidebarForeground,
        t,
      )!,
      sidebarPrimary: Color.lerp(sidebarPrimary, other.sidebarPrimary, t)!,
      sidebarPrimaryForeground: Color.lerp(
        sidebarPrimaryForeground,
        other.sidebarPrimaryForeground,
        t,
      )!,
      sidebarAccent: Color.lerp(sidebarAccent, other.sidebarAccent, t)!,
      sidebarAccentForeground: Color.lerp(
        sidebarAccentForeground,
        other.sidebarAccentForeground,
        t,
      )!,
      sidebarBorder: Color.lerp(sidebarBorder, other.sidebarBorder, t)!,
      sidebarRing: Color.lerp(sidebarRing, other.sidebarRing, t)!,
    );
  }
}

// ──────────────────────────────────────────
// TweakcnRadius (ThemeExtension)
// ──────────────────────────────────────────

class TweakcnRadius extends ThemeExtension<TweakcnRadius> {
  final double sm;
  final double md;
  final double lg;
  final double xl;

  const TweakcnRadius({
    required this.sm,
    required this.md,
    required this.lg,
    required this.xl,
  });

  static const standard = TweakcnRadius(sm: 6.0, md: 8.0, lg: 10.0, xl: 14.0);

  @override
  TweakcnRadius copyWith({double? sm, double? md, double? lg, double? xl}) {
    return TweakcnRadius(
      sm: sm ?? this.sm,
      md: md ?? this.md,
      lg: lg ?? this.lg,
      xl: xl ?? this.xl,
    );
  }

  @override
  TweakcnRadius lerp(covariant TweakcnRadius? other, double t) {
    if (other == null) return this;
    return TweakcnRadius(
      sm: sm + (other.sm - sm) * t,
      md: md + (other.md - md) * t,
      lg: lg + (other.lg - lg) * t,
      xl: xl + (other.xl - xl) * t,
    );
  }
}

// ──────────────────────────────────────────
// TweakcnShadows (ThemeExtension)
// ──────────────────────────────────────────

class TweakcnShadows extends ThemeExtension<TweakcnShadows> {
  final List<BoxShadow> shadow2xs;
  final List<BoxShadow> shadowXs;
  final List<BoxShadow> shadowSm;
  final List<BoxShadow> shadow;
  final List<BoxShadow> shadowMd;
  final List<BoxShadow> shadowLg;
  final List<BoxShadow> shadowXl;
  final List<BoxShadow> shadow2xl;

  const TweakcnShadows({
    required this.shadow2xs,
    required this.shadowXs,
    required this.shadowSm,
    required this.shadow,
    required this.shadowMd,
    required this.shadowLg,
    required this.shadowXl,
    required this.shadow2xl,
  });

  static const light = TweakcnShadows(
    shadow2xs: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x03000000),
      ),
    ],
    shadowXs: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x03000000),
      ),
    ],
    shadowSm: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x08000000),
      ),
      BoxShadow(
        offset: Offset(1.0, 1.0),
        blurRadius: 2.0,
        spreadRadius: -1.0,
        color: Color(0x08000000),
      ),
    ],
    shadow: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x08000000),
      ),
      BoxShadow(
        offset: Offset(1.0, 1.0),
        blurRadius: 2.0,
        spreadRadius: -1.0,
        color: Color(0x08000000),
      ),
    ],
    shadowMd: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x08000000),
      ),
      BoxShadow(
        offset: Offset(1.0, 2.0),
        blurRadius: 4.0,
        spreadRadius: -1.0,
        color: Color(0x08000000),
      ),
    ],
    shadowLg: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x08000000),
      ),
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 6.0,
        spreadRadius: -1.0,
        color: Color(0x08000000),
      ),
    ],
    shadowXl: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x08000000),
      ),
      BoxShadow(
        offset: Offset(1.0, 8.0),
        blurRadius: 10.0,
        spreadRadius: -1.0,
        color: Color(0x08000000),
      ),
    ],
    shadow2xl: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x12000000),
      ),
    ],
  );

  static const dark = TweakcnShadows(
    shadow2xs: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x03000000),
      ),
    ],
    shadowXs: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x03000000),
      ),
    ],
    shadowSm: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x08000000),
      ),
      BoxShadow(
        offset: Offset(1.0, 1.0),
        blurRadius: 2.0,
        spreadRadius: -1.0,
        color: Color(0x08000000),
      ),
    ],
    shadow: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x08000000),
      ),
      BoxShadow(
        offset: Offset(1.0, 1.0),
        blurRadius: 2.0,
        spreadRadius: -1.0,
        color: Color(0x08000000),
      ),
    ],
    shadowMd: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x08000000),
      ),
      BoxShadow(
        offset: Offset(1.0, 2.0),
        blurRadius: 4.0,
        spreadRadius: -1.0,
        color: Color(0x08000000),
      ),
    ],
    shadowLg: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x08000000),
      ),
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 6.0,
        spreadRadius: -1.0,
        color: Color(0x08000000),
      ),
    ],
    shadowXl: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x08000000),
      ),
      BoxShadow(
        offset: Offset(1.0, 8.0),
        blurRadius: 10.0,
        spreadRadius: -1.0,
        color: Color(0x08000000),
      ),
    ],
    shadow2xl: [
      BoxShadow(
        offset: Offset(1.0, 4.0),
        blurRadius: 5.0,
        spreadRadius: 0.0,
        color: Color(0x12000000),
      ),
    ],
  );

  @override
  TweakcnShadows copyWith({
    List<BoxShadow>? shadow2xs,
    List<BoxShadow>? shadowXs,
    List<BoxShadow>? shadowSm,
    List<BoxShadow>? shadow,
    List<BoxShadow>? shadowMd,
    List<BoxShadow>? shadowLg,
    List<BoxShadow>? shadowXl,
    List<BoxShadow>? shadow2xl,
  }) {
    return TweakcnShadows(
      shadow2xs: shadow2xs ?? this.shadow2xs,
      shadowXs: shadowXs ?? this.shadowXs,
      shadowSm: shadowSm ?? this.shadowSm,
      shadow: shadow ?? this.shadow,
      shadowMd: shadowMd ?? this.shadowMd,
      shadowLg: shadowLg ?? this.shadowLg,
      shadowXl: shadowXl ?? this.shadowXl,
      shadow2xl: shadow2xl ?? this.shadow2xl,
    );
  }

  @override
  TweakcnShadows lerp(covariant TweakcnShadows? other, double t) {
    if (other == null) return this;
    return TweakcnShadows(
      shadow2xs: BoxShadow.lerpList(shadow2xs, other.shadow2xs, t) ?? [],
      shadowXs: BoxShadow.lerpList(shadowXs, other.shadowXs, t) ?? [],
      shadowSm: BoxShadow.lerpList(shadowSm, other.shadowSm, t) ?? [],
      shadow: BoxShadow.lerpList(shadow, other.shadow, t) ?? [],
      shadowMd: BoxShadow.lerpList(shadowMd, other.shadowMd, t) ?? [],
      shadowLg: BoxShadow.lerpList(shadowLg, other.shadowLg, t) ?? [],
      shadowXl: BoxShadow.lerpList(shadowXl, other.shadowXl, t) ?? [],
      shadow2xl: BoxShadow.lerpList(shadow2xl, other.shadow2xl, t) ?? [],
    );
  }
}

// ──────────────────────────────────────────
// TweakcnTheme
// ──────────────────────────────────────────

class TweakcnTheme {
  TweakcnTheme._();

  static ThemeData get light => ThemeData(
    brightness: Brightness.light,
    colorScheme: _lightColorScheme,
    fontFamily: 'Roboto',
    extensions: [
      TweakcnColors.light,
      TweakcnRadius.standard,
      TweakcnShadows.light,
    ],
  );

  static ThemeData get dark => ThemeData(
    brightness: Brightness.dark,
    colorScheme: _darkColorScheme,
    fontFamily: 'Roboto',
    extensions: [
      TweakcnColors.dark,
      TweakcnRadius.standard,
      TweakcnShadows.dark,
    ],
  );
}

// ──────────────────────────────────────────
// BuildContext Extension
// ──────────────────────────────────────────

extension TweakcnBuildContext on BuildContext {
  TweakcnColors get tweakcnColors => Theme.of(this).extension<TweakcnColors>()!;
  TweakcnRadius get tweakcnRadius => Theme.of(this).extension<TweakcnRadius>()!;
  TweakcnShadows get tweakcnShadows =>
      Theme.of(this).extension<TweakcnShadows>()!;
}
